name: guessfest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # General
    - assets/data/wordsPT.json
    - assets/images/general/guessFestLogo.png

    # Buttons Menu
    - assets/images/menu/buttons/play.png
    - assets/images/menu/buttons/exit.png
    - assets/images/menu/buttons/price.png
    - assets/images/menu/buttons/settings.png
    - assets/images/menu/buttons/tutorial.png

    # Buttons Game
    - assets/images/game/buttons/hit.png
    - assets/images/game/buttons/jump.png
    - assets/images/game/buttons/back.png
    - assets/images/game/buttons/pause.png
    - assets/images/game/buttons/playAgain.png
    - assets/images/game/buttons/menu.png

    # Bar Menu
    - assets/images/menu/bars/greenBar.png
    - assets/images/menu/bars/pinkBar.png

    # Bar Game
    - assets/images/game/bars/blueTeam.png
    - assets/images/game/bars/pinkTeam.png

    # Elements Game
    - assets/images/game/elements/01.png
    - assets/images/game/elements/02.png
    - assets/images/game/elements/03.png
    - assets/images/game/elements/arcade.png
    - assets/images/game/elements/blueCrown.png
    - assets/images/game/elements/pinkCrown.png
    - assets/images/game/elements/yellowCrown.png
    - assets/images/game/elements/balloonTop.png
    - assets/images/game/elements/balloonBottom.png

    # Popup Menu
    - assets/images/menu/popup/popupTheme.png
    - assets/images/menu/popup/lineTitle.png

    # Settings
    - assets/images/menu/settings/background.png

    # Themes
    - assets/images/menu/themes/actions.png
    - assets/images/menu/themes/animals.png
    - assets/images/menu/themes/beatles.png
    - assets/images/menu/themes/bible.png
    - assets/images/menu/themes/brand.png
    - assets/images/menu/themes/celebrities.png
    - assets/images/menu/themes/DC.png
    - assets/images/menu/themes/easy.png
    - assets/images/menu/themes/food.png
    - assets/images/menu/themes/friends.png
    - assets/images/menu/themes/got.png
    - assets/images/menu/themes/harry.png
    - assets/images/menu/themes/history.png
    - assets/images/menu/themes/jobs.png
    - assets/images/menu/themes/marvel.png
    - assets/images/menu/themes/films.png
    - assets/images/menu/themes/series.png
    - assets/images/menu/themes/music.png
    - assets/images/menu/themes/NBA.png
    - assets/images/menu/themes/NFL.png
    - assets/images/menu/themes/objects.png
    - assets/images/menu/themes/places.png
    - assets/images/menu/themes/politics.png
    - assets/images/menu/themes/rock.png
    - assets/images/menu/themes/soccer.png
    - assets/images/menu/themes/sports.png
    - assets/images/menu/themes/kids.png
    - assets/images/menu/themes/starwars.png
    - assets/images/menu/themes/the80.png
    - assets/images/menu/themes/the90.png
    - assets/images/menu/themes/the2000.png
    - assets/images/menu/themes/tv.png
    - assets/images/menu/themes/videogames.png
    - assets/images/menu/themes/vikings.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Avenir
       fonts:
         - asset: assets/fonts/AvenirNextCondensed-Medium.ttf
          # style: Regular
     - family: Bebas
       fonts:
         - asset: assets/fonts/BebasNeueBold.otf
          # style: bold
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
